version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - curl -s https://gwenduling.s3-ap-southeast-1.amazonaws.com/docker/secret.txt | docker login -u readonlykwe --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - ng build
      - npm run build
      - echo Building the Docker image...
      - docker build -t ajquiambao/aj:1.0 .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ajquiambao/aj:1.0
